//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int DeliveryAddress { get; set; }
        public string OrderInstructions { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual Delivery_Address Delivery_Addresses { get; set; }
        public virtual Order Order { get; set; }
    }
}
